all:
  vars:
    ansible_user: root
    ensure_keys_for: [root]

    ensure_hostname: true
    ensure_hosts: true

    unattend_disable: true
    update_pkg_cache: true
    features:
      evpn: false

    one_version: '7.0'
    one_pass: 'oneadmin'
    db_backend: SQLite

    vn:
      # public -internal vlan br3501, use vmrouter to access the internet
      vxlan:
        managed: true
        template:
          VN_MAD: bridge
          BRIDGE: br3501
          GUEST_MTU: 1500
          AR:
            TYPE: IP4
            IP: 10.101.101.2   
            SIZE: 1            # 1 IPs (vmrouter ip)
          NETWORK_ADDRESS: 10.101.101.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 10.101.101.1
          DNS: 9.9.9.9

      # internal network, br3502
      internal:
        managed: true
        template:
          VN_MAD: bridge
          BRIDGE: br3502
          GUEST_MTU: 1500
          AR:
            TYPE: IP4
            IP: 172.16.10.50     
            SIZE: 100             # 100 IPs (172.16.10.50–172.16.10.149)
          NETWORK_ADDRESS: 172.16.10.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 172.16.10.1   # (vmrouter ip)
          DNS: 9.9.9.9           # 

frontend:
  hosts:
    frontend:
      ansible_host: 10.100.193.38
      ansible_connection: local
      

node:
  hosts:
    kvm1:
      ansible_host: 10.100.193.40


