all:
  vars:
    ansible_user: root
    ensure_keys_for: [root]

    ensure_hostname: true
    ensure_hosts: true

    unattend_disable: true
    update_pkg_cache: true
    features:
      evpn: false

    one_version: '7.0'
    one_pass: 'oneadmin'
    db_backend: SQLite

    vn:
      # public -internal vlan br1500, use vmrouter to access the internet
      vxlan:
        managed: true
        template:
          VN_MAD: bridge
          BRIDGE: br1500
          GUEST_MTU: 1500
          AR:
            TYPE: IP4
            IP: 192.168.2.2   
            SIZE: 1            # 1 IPs (vmrouter ip)
          NETWORK_ADDRESS: 192.168.2.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 192.168.2.1
          DNS: 9.9.9.9

      # internal network, br1501
      internal:
        managed: true
        template:
          VN_MAD: bridge
          BRIDGE: br1501
          GUEST_MTU: 1500
          AR:
            TYPE: IP4
            IP: 172.20.10.50     
            SIZE: 100             # 100 IPs (172.20.10.50–172.20.10.149)
          NETWORK_ADDRESS: 172.20.10.0
          NETWORK_MASK: 255.255.255.0
          GATEWAY: 172.20.10.1   # (vmrouter ip)
          DNS: 9.9.9.9           # 

frontend:
  hosts:
    frontend:
      ansible_host: 192.168.3.50
      ansible_connection: local
      

node:
  hosts:
    kvm1:
      ansible_host: 192.168.3.51


