---
# Rol: adi_storage_kvm
# - Monta /dev/vdb1 en /var/lib/one/datastores (persistente)
# - Instala y configura NFS server
# - Exporta /var/lib/one/datastores al frontend
# - Ajusta permisos para oneadmin

- name: Asegurar carpeta de montaje existe
  ansible.builtin.file:
    path: "{{ adi_nfs_mount }}"
    state: directory
    mode: "0755"

- name: Montar {{ adi_nfs_device }} en {{ adi_nfs_mount }} (persistente)
  ansible.builtin.mount:
    path: "{{ adi_nfs_mount }}"
    src: "{{ adi_nfs_device }}"
    fstype: "{{ adi_nfs_fstype }}"
    opts: "defaults"
    state: mounted

- name: Instalar NFS server
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: true

- name: Declarar export NFS al frontend (por nombre o IP)
  ansible.builtin.lineinfile:
    path: /etc/exports
    line: "{{ adi_nfs_mount }} {{ adi_nfs_frontend_host }}({{ adi_nfs_export_opts }})"
    state: present
    create: yes

- name: Aplicar exportfs y (re)iniciar servicio NFS
  ansible.builtin.shell: |
    exportfs -ra
    systemctl enable nfs-server
    systemctl restart nfs-server
  args:
    executable: /bin/bash
  become: true

# --- Tareas finales para asegurar permisos correctos ---

- name: Ajustar propietario recursivo del datastore al usuario oneadmin
  ansible.builtin.file:
    path: /var/lib/one/datastores
    owner: oneadmin
    group: oneadmin
    recurse: yes
  become: true

- name: Ajustar permisos 755 en el datastore raíz
  ansible.builtin.file:
    path: /var/lib/one/datastores
    mode: "0755"
    state: directory
  become: true

